services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
  migrate:
    build:
      context: ./server
      target: migrate
    environment:
      LIBRARIAN_DATABASE_URL: ${LIBRARIAN_DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: 'no'
  server:
    build:
      context: ./server
      target: runtime
    environment:
      PORT: ${PORT}
      LIBRARIAN_DATABASE_URL: ${LIBRARIAN_DATABASE_URL}
      OPEN_LIBRARY:API_URL: ${OPEN_LIBRARY_API_URL}
      OPEN_LIBRARY_COVERS_API_URL: ${OPEN_LIBRARY_COVERS_API_URL}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
volumes:
  db-data:
