/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Books {
  created_at: Generated<Timestamp>;
  external_id: string | null;
  id: Generated<string>;
  isbn: string;
  source: string | null;
  title: string;
}

export interface DB {
  books: Books;
}
